---
- name: Create required certificate authority and certificates for kubernetes cluster
  gather_facts: false
  hosts: 127.0.0.1
  # vars:
  #   - GITHUB_URL: "https://github.com/etcd-io/etcd/releases/download"
  #   - ETCD_VERSION: "v3.5.9"
  tasks:
    - name: Generate CA private key and certificate
      ansible.builtin.shell: |
        cfssl gencert -initca ca-csr.json | cfssljson -bare ca
      args:
        chdir: /etc/kubernetes/pki
      register: ca
      # delegate_to: localhost
