---
- name: "Set kubectl config and test cluster connection"
  gather_facts: false
  hosts: localhost
  vars_files:
    - vars.yml
  vars:
    - SOURCE_PATH: "../../030-certificate-authority"
  tasks:
    - name: "Set cluster in kubectl config"
      ansible.builtin.shell:
        cmd: |
          kubectl config set-cluster kubernetes-the-hard-way \
            --certificate-authority={{ SOURCE_PATH }}/ca.pem \
            --embed-certs=true \
            --server=https://{{ loadbalancer_public_ip }}:6443

    - name: "Set admin credentials for kubectl"
      ansible.builtin.shell:
        cmd: |
          kubectl config set-credentials admin \
            --client-certificate={{ SOURCE_PATH }}/admin.pem \
            --client-key={{ SOURCE_PATH }}/admin-key.pem

    - name: "Set kubectl context for cluster"
      ansible.builtin.shell:
        cmd: |
          kubectl config set-context kubernetes-the-hard-way \
            --cluster=kubernetes-the-hard-way \
            --user=admin

    - name: "Set kubectl context to default"
      ansible.builtin.shell:
        cmd: |
          kubectl config use-context kubernetes-the-hard-way

    - name: "Test kubectl cluster connection"
      ansible.builtin.shell:
        cmd: |
          kubectl get nodes
      register: kubectl_status
      # until: kubectl_status is success
      # delay: 10
      # retries: 10
    
    - name: "Print kubectl cluster connection status"
      ansible.builtin.debug:
        msg: "{{ kubectl_status.stdout_lines }}"